plugins:
- jekyll-datapage-generator
  
page_gen:
- data: 'theta.caboodle'
  dir: 'representations'
  title: 'Simple groups'
  template: 'representation'
  index_files: false
  name: 'name'
  debug: 'true'